### ISSUE TITLE
ROS建模仿真（四）：实现机器人自主导航和实时二维码识别

### ISSUE THREAD

**Issue by Feng-DDXY** [Feng-DDXY/blogs#5]
**使用版本：Ubuntu 16.04  ROS Kinetic（已安装）**

本篇结合上一篇进行，使用同一个功能包

>以下步骤自行完成（仅附终端命令）
>1.在已有工作空间下创建功能包my_robot_2
>2.导入urdf、xacro、gazebo_ros、gazebo_ros_control、gazebo_plugins作为该功能包的依赖项

```bash
catkin_create_pkg my_robot_2 urdf xacro gazebo_ros gazebo_ros_control gazebo_plugins
cd ~/catkin_ws
catkin_make
source devel/setup.bash   //添加环境变量
```

！！！！！！！！但是需要新建文件夹

**在my_robot_2文件夹路径下**新建3个文件夹，规范化管理文件：

```bash
mkdir param scripts
```

删除文件夹：（放在这万一路径新建错了记得删一下）

```bash
rm -r param scripts
```

加上上次的一共六个文件：

![image-20241209030345807](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426229.png)

## 1.通过AMCL对机器人进行位置定位

AMCL定位系统和move_base导航集成在navigation里，这里下载一下：

```bash
sudo apt-get install ros-kinetic-navigation
```

在launch文件夹下新建amcl.launch文件，并输入以下内容：

该文件进行了定位信息的设置

```xml
<launch>
<node pkg="amcl" type="amcl" name="amcl" output="screen">
  <!-- Publish scans from best pose at a max of 10 Hz -->
  <param name="odom_model_type" value="diff"/><!-- 里程计模式为差分 -->
  <param name="odom_alpha5" value="0.1"/>
  <param name="transform_tolerance" value="0.2" />
  <param name="gui_publish_rate" value="10.0"/>
  <param name="laser_max_beams" value="30"/>
  <param name="min_particles" value="500"/>
  <param name="max_particles" value="5000"/>
  <param name="kld_err" value="0.05"/>
  <param name="kld_z" value="0.99"/>
  <param name="odom_alpha1" value="0.2"/>
  <param name="odom_alpha2" value="0.2"/>
  <!-- translation std dev, m -->
  <param name="odom_alpha3" value="0.8"/>
  <param name="odom_alpha4" value="0.2"/>
  <param name="laser_z_hit" value="0.5"/>
  <param name="laser_z_short" value="0.05"/>
  <param name="laser_z_max" value="0.05"/>
  <param name="laser_z_rand" value="0.5"/>
  <param name="laser_sigma_hit" value="0.2"/>
  <param name="laser_lambda_short" value="0.1"/>
  <param name="laser_lambda_short" value="0.1"/>
  <param name="laser_model_type" value="likelihood_field"/>
  <!-- <param name="laser_model_type" value="beam"/> -->
  <param name="laser_likelihood_max_dist" value="2.0"/>
  <param name="update_min_d" value="0.2"/>
  <param name="update_min_a" value="0.5"/>

  <param name="odom_frame_id" value="odom"/><!-- 里程计坐标系 -->
  <param name="base_frame_id" value="base_footprint"/><!-- 添加机器人基坐标系 -->

</node>
</launch>
```

在launch文件夹下新建navigation.launch文件，并输入以下内容：

```xml
<launch>
    <!-- 将 URDF 文件的内容加载到参数服务器 -->
    <param name="robot_description" command="xacro $(find my_robot_2)/urdf/my_car_camera.urdf.xacro" />

    <!-- 启动 Gazebo 仿真环境 -->
    <!-- 其中第二行是添加制作的world文件 -->
    <include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="world_name" value="$(find my_robot_2)/worlds/mymap2.world" />
    </include>
    
    <!-- 在 Gazebo 中显示机器人模型 -->
    <node pkg="gazebo_ros" type="spawn_model" name="model" args="-urdf -model mycar -param robot_description" />
    
    <!-- 启动关节状态发布器 -->
    <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
    
    <!-- 启动机器人状态发布器，发布TF -->
    <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />

    <!-- 启动rviz -->
    <node pkg="rviz" type="rviz" name="rviz"  />
    
    <!-- 加载地图服务 -->
    <arg name="map" default="mymap.yaml" />
    <node pkg="map_server" type="map_server" name="map_server" args="$(find my_robot_2)/map/map.yaml" />

    <!-- 启动AMCL节点 -->
    <include file="$(find my_robot_2)/launch/amcl.launch" />

    

</launch>

```

这个代码把rviz集成在里面一起启动了，可能打开的一瞬间巨卡（

如果想手动打开可以删除那行并自行输终端命令

运行一下：

```bash
roslaunch my_robot_2 navigation.launch
```

![image-20241208155114348](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426230.png)

在rviz中分别加入如下4个，其中雷达、地图、PoseArray需要导入话题

![image-20241208155228843](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426231.png)

如果能成功看到PoseArray进行定位的红色箭头，即成功实现了通过AMCL进行机器人的位置定位

## 2.实现机器人到指定位置自主导航

接下来通过AMCL提供的定位信息进行路径规划：

在launch文件夹下新建move_base.launch文件，并输入以下内容：

这个节点是移动机器人到目标位置的常用节点（路径规划、障碍物避让和局部控制）

```xml
<launch>

    <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen" clear_params="true">
        <rosparam file="$(find my_robot_2)/param/costmap_common_params.yaml" command="load" ns="global_costmap" />
        <rosparam file="$(find my_robot_2)/param/costmap_common_params.yaml" command="load" ns="local_costmap" />
        <rosparam file="$(find my_robot_2)/param/local_costmap_params.yaml" command="load" />
        <rosparam file="$(find my_robot_2)/param/global_costmap_params.yaml" command="load" />
        <rosparam file="$(find my_robot_2)/param/base_local_planner_params.yaml" command="load" />
    </node>

</launch>
```

1. `costmap_common_params.yaml`：定义了全局和局部代价地图的常见参数
2. `local_costmap_params.yaml`：定义了局部代价地图的具体参数
3. `global_costmap_params.yaml`：定义了全局代价地图的具体参数
4. `base_local_planner_params.yaml`：定义了局部路径规划器的参数，通常用于控制机器人如何移动到目标位置

接着从官方移植这些配置代码：

在功能包下的param目录新建costmap_common_params.yaml文件，并输入：

```yaml
#机器人几何参，如果机器人是圆形，设置 robot_radius,如果是其他形状设置 footprint
robot_radius: 0.12 #圆形
# footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]] #其他形状

obstacle_range: 3.0 # 用于障碍物探测，比如: 值为 3.0，意味着检测到距离小于 3 米的障碍物时，就会引入代价地图
raytrace_range: 3.5 # 用于清除障碍物，比如：值为 3.5，意味着清除代价地图中 3.5 米以外的障碍物


#膨胀半径，扩展在碰撞区域以外的代价区域，使得机器人规划路径避开障碍物
inflation_radius: 0.2
#代价比例系数，越大则代价值越小
cost_scaling_factor: 3.0

#地图类型
map_type: costmap
#导航包所需要的传感器
observation_sources: scan
#对传感器的坐标系和数据进行配置。这个也会用于代价地图添加和清除障碍物。例如，你可以用激光雷达传感器用于在代价地图添加障碍物，再添加kinect用于导航和清除障碍物。
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
```

在功能包下的param目录新建local_costmap_params.yaml文件，并输入：

```yaml
global_costmap:
  global_frame: map #地图坐标系
  robot_base_frame: base_footprint #机器人坐标系
  # 以此实现坐标变换

  update_frequency: 1.0 #代价地图更新频率
  publish_frequency: 1.0 #代价地图的发布频率
  transform_tolerance: 0.5 #等待坐标变换发布信息的超时时间

  static_map: true # 是否使用一个地图或者地图服务器来初始化全局代价地图，如果不使用静态地图，这个参数为false.
```

在功能包下的param目录新建global_costmap_params.yaml文件，并输入：

```yaml
local_costmap:
  global_frame: odom #里程计坐标系
  robot_base_frame: base_footprint #机器人坐标系

  update_frequency: 10.0 #代价地图更新频率
  publish_frequency: 10.0 #代价地图的发布频率
  transform_tolerance: 0.5 #等待坐标变换发布信息的超时时间

  static_map: false  #不需要静态地图，可以提升导航效果
  rolling_window: true #是否使用动态窗口，默认为false，在静态的全局地图中，地图不会变化
  width: 3 # 局部地图宽度 单位是 m
  height: 3 # 局部地图高度 单位是 m
  resolution: 0.05 # 局部地图分辨率 单位是 m，一般与静态地图分辨率保持一致
```

在功能包下的param目录新建base_local_planner_params.yaml文件，并输入：

```yaml
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.5 # X 方向最大速度
  min_vel_x: 0.1 # X 方向最小速速

  max_vel_theta:  1.0 # 
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0 # X 加速限制
  acc_lim_y: 0.0 # Y 加速限制
  acc_lim_theta: 0.6 # 角速度加速限制

# Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: false

# Forward Simulation Parameters，前进模拟参数
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
```

最后将navigation.launch文件修改一下：

在之前的AMCL节点后添加了调用刚刚编写的move_base.launch文件进行启动move_base节点：

```xml
<launch>
    <!-- 将 URDF 文件的内容加载到参数服务器 -->
    <param name="robot_description" command="xacro $(find my_robot_2)/urdf/my_car_camera.urdf.xacro" />

    <!-- 启动 Gazebo 仿真环境 -->
    <!-- 其中第二行是添加制作的world文件 -->
    <include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="world_name" value="$(find my_robot_2)/worlds/mymap2.world" />
    </include>
    
    <!-- 在 Gazebo 中显示机器人模型 -->
    <node pkg="gazebo_ros" type="spawn_model" name="model" args="-urdf -model mycar -param robot_description" />
    
    <!-- 启动关节状态发布器 -->
    <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
    
    <!-- 启动机器人状态发布器，发布TF -->
    <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />

    <!-- 加载地图服务 -->
    <arg name="map" default="mymap.yaml" />
    <node pkg="map_server" type="map_server" name="map_server" args="$(find my_robot_2)/map/map.yaml" />

    <!-- 启动AMCL节点 -->
    <include file="$(find my_robot_2)/launch/amcl.launch" />

    <!-- 启动move—_base节点  机器人参数 局部规划器 -->
    <include file="$(find my_robot_2)/launch/move_base.launch" />

    <!-- 启动rviz -->
    <node pkg="rviz" type="rviz" name="rviz"  />

    

</launch>

```

在运行前把之前的urdf里面的my_base.urdf.xacro文件修改一下：这里代码是两个轮子的顺序

![image-20241208172243511](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426232.png)

运行一下：

```bash
roslaunch my_robot_2 navigation.launch
```

点击上方的2D Naw Goal可以在地图上给小车设定目标点，如果前面没错的话这时就能看见小车在自行朝那个目标移动

![image-20241208171440300](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426233.png)

如果地图跟着小车转，将Fixed Frame设置为map，可以加入里程计（Odometry）查看小车的运动方向，效果更直观

![image-20241208172626320](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426234.png)

## 3.在已有的世界模型中加入二维码图片

首先打开一个空的gazebo

gazebo

在gazebo中左上角进入Building Editor，画一个平平无奇的墙（只是给地图加点东西保存罢了）

model名字设置为qrcodewall

![image-20241208235349929](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426235.png)

在File里面点Save As，应该会保存到默认地址下：保存好了后即可关闭gazebo

在默认地址，即building_editor_models下可以看到有一个新建的文件夹qrcodewall 就是我们刚刚保存那个

![image-20241208235504421](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426236.png)

把这个文件夹移动到/home/用户名/.gazebo/models路径下，如下所示：

![image-20241208235546132](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426237.png)

点击进入qrcodewall文件夹，打开终端，输入以下命令：

```bash
mkdir -p materials/scripts materials/textures
gedit materials/scripts/aruco.material
```

然后编辑aruco.material文件，输入以下内容：

这个是通过材质系统定义材质外观，材质名字叫Gazebo/aruco-1，导入了纹理文件 `aruco-1.png`（二维码文件）

```
import * from "grid.material"
material Gazebo/aruco-1
{
  receive_shadows on
 
  technique
  {
    pass
    {
      ambient 0.5 0.5 0.5 1.000000
 
      texture_unit
      {
        texture aruco-1.png
      }
    }
  }
}


```

保存并退出后继续在qrcodewall文件夹路径终端内输入：

```bash
gedit model.sdf
```

编辑文件内容为：

这里是gazeobo的模型文件，名为 `qrcodewall` ，内容是定义了一个宽2.5 米、高 0.15 米、长 2.5 米的长方体

主要代码是script指定的材质使用的脚本路径，并且连接Gazebo/aruco-1材质名

```xml
<?xml version='1.0'?>
<sdf version='1.7'>
  <model name='qrcodewall'>
    <pose>-1.66123 0.5775 0 0 -0 0</pose>
    <link name='Wall_8'>
      <collision name='Wall_8_Collision'>
        <geometry>
          <box>
            <size>2.5 0.15 2.5</size>
          </box>
        </geometry>
        <pose>0 0 1.25 0 -0 0</pose>
      </collision>
      <visual name='Wall_8_Visual'>
        <pose>0 0 1.25 0 -0 0</pose>
        <geometry>
          <box>
            <size>2.5 0.15 2.5</size>
          </box>
        </geometry>
        <material>
          <script>
         <uri>model://qrcodewall/materials/scripts</uri>
         <uri>model://qrcodewall/materials/textures</uri>
         <name>Gazebo/aruco-1</name>
          </script>
          <ambient>1 1 1 1</ambient>
        </material>
        <meta>
          <layer>0</layer>
        </meta>
      </visual>
      <pose>-0.541194 0 0 0 -0 0.523599</pose>
    </link>
    <static>1</static>
  </model>
</sdf>

```

两个文件编辑完记得保存并退出

接着到materials/textures文件夹（刚刚通过命令行创建了）下放入你的二维码图片，命名为aruco-1.png，如下所示

![image-20241209002501190](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426239.png)

输入以下终端命令打开上一节制作的地图mymap2

```
gazebo  /home/用户名/catkin_ws/src/my_robot_2/worlds/mymap2.world
```

在insert里面能看到刚刚新建的qrcodewall模型，将制作的qrcodewall放入原来的mymap2世界中

通过上方的旋转和平移将其放到理想地点

![image-20241209001310455](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426240.png)

调整完毕后点击右上角的Save World As 

在之前的worlds路径下保存为mymap3.world，即做好了一个有二维码的地图，命名为mymap3.world

如果后期想换二维码可以改材质里面的图片名称，也可以直接懒惰的改图片，将新图片命名成aruco-1.png替换原来那张即可

图片效果如下：

![image-20241209001451635](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426241.png)

就可以输入终端命令再次打开查看有二维码的地图：

```
gazebo  /home/用户名/catkin_ws/src/my_robot_2/worlds/mymap3.world
```

## 4.机器人结合摄像头模块进行二维码识别

这里需要安装一下二维码识别库和opencv库（如果报错自己解决一下吧，我在报错中稀里糊涂装下来了）

建议现在在虚拟机上搞个快照备份一手

```bash
sudo apt install python-pip
sudo apt-get install libzbar-dev
pip install zbar
sudo apt-get install python-opencv
```

在之前的navigation.lanuch文件里面将运行的mymap2改成mymap3，即地图模型加载刚刚制作的带二维码的地图

![image-20241209004424284](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426242.png)

在功能包的scripts文件夹下新建一个python文件，名字随意，例如我的是sss.py

输入以下代码：

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from sensor_msgs.msg import Image
import cv2
from cv_bridge import CvBridge
import zbar
import numpy as np

def image_callback(msg):
    bridge = CvBridge()
    # 将 ROS 图像消息转换为 OpenCV 图像
    frame = bridge.imgmsg_to_cv2(msg, "bgr8")

    # 将图像转换为灰度图像
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 创建 zbar 图像对象
    scanner = zbar.ImageScanner()
    scanner.parse_config('enable')

    # 将 OpenCV 图像转换为 zbar 可用的图像格式
    raw = gray.tostring()
    zbar_image = zbar.Image(gray.shape[1], gray.shape[0], 'Y800', raw)

    # 执行解码
    scanner.scan(zbar_image)

    # 打印二维码数据
    for decoded in zbar_image:
        qr_data = decoded.data.decode('utf-8')
        rospy.loginfo("二维码数据：%s", qr_data.encode('utf-8'))

def main():
    rospy.init_node('qr_code_detector')
    rospy.Subscriber('/camera/image_raw', Image, image_callback)  # 修改为你的图像话题
    rospy.spin()

if __name__ == "__main__":
    main()
```

在scripts路径下运行你的python脚本：（需要将python脚本设置为可执行文件）

```bash
rosrun my_robot_2 sss.py
```

到此一切前置工作都结束了，接下来看看效果：

运行命令：

```bash
roslaunch my_robot_2 navigation.launch
```

在另一个终端运行键盘控制指令（个人更喜欢键盘控制移动，自主导航又慢又控制不了方向，emm也可能是我不会）

```bash
rosrun teleop_twist_keyboard teleop_twist_keyboard.py
```

打开rviz里面的摄像头模组，可以看到实时回传画面：

![image-20241209041714574](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426243.png)

通过自主导航或者键盘控制将小车往摄像头方向靠拢

当二维码出现在画面中时 之前python文件的终端便会返回二维码识别结果

![image-20241209042211567](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426244.png)

效果如下：

![image-20241209025306248](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426245.png)

将输出语句rospy.loginfo改成rospy.logwarn，重新运行可以看到输出变成了WARN级别：

![image-20241209042449338](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426246.png)

![image-20241209030220926](https://raw.githubusercontent.com/Feng-DDXY/img_cloud/main/202412090426247.png)
